### ISSUE TITLE
请问web登陆的账号秘密是多少？

### ISSUE THREAD

**Issue by bigbigbigfish** [goaiquant/GOAi#1]
请问web登陆的账号秘密是多少？
另外，里面有2个jar包，这个工程不是里面说的完全开源的？

**Comment by pipione** [comment]
范强林Hi  我也是这个项目的关注者  web 的登陆密码在jar 包里面 使用压缩工具打开就能看见-------- 原始邮件 --------主题：[goaiquant/GOAi] 请问web登陆的账号秘密是多少？ (#1)发件人：bigbigbigfish 收件人：goaiquant/GOAi 抄送：Subscribed 请问web登陆的账号秘密是多少？

另外，里面有2个jar包，这个工程不是里面说的完全开源的？

**Comment by bigbigbigfish** [comment]
> 范强林Hi  我也是这个项目的关注者  web 的登陆密码在jar 包里面 使用压缩工具打开就能看见-------- 原始邮件 --------主题：[goaiquant/GOAi] 请问web登陆的账号秘密是多少？ (#1)发件人：bigbigbigfish 收件人：goaiquant/GOAi 抄送：Subscribed 请问web登陆的账号秘密是多少？ 另外，里面有2个jar包，这个工程不是里面说的完全开源的？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

请问具体是什么账号？解压后没有账号

**Comment by pipione** [comment]
@bigbigbigfish 

custom:
  admin:
    email: goai
    password: goai123456

**Comment by GoaiSystem** [comment]
启动 好批处理 命令行就有提示的
